package money.calculator.MoneyCalculator.model.insurance;

public enum CarModel {
    AUDI, MERCEDES, BMW, FERRARI, PORSHE, TESLA, FIAT, DAEWOO, SUBARU, SUZUKI, FORD,
    MITSUBISHI, KIA, MAZDA, NISSAN, OPEL, RENAULT, TOYOTA,
    VOLKSWAGEN, VOLVO, ZAZ_ZAPOROZHEC, CHEVROLET, HYUNDAI, DODGE, NONE
}
