package money.calculator.MoneyCalculator.model.insurance;

public enum Job {
    NONE, ACTOR, ARCHITECT, ACCOUNTANT, AUTHOR, BAKER, BUILDER, BUTCHER, DOCTOR, CLEANER, DRIVER, ELECTRICIAN,
    HAIRDRESSER, LAWYER, FARMER, FIREFIGHTER, FACTORY_WORKER, MECHANIC, MODEL, PILOT, POLITICIAN, POLICEMAN, SOLDIER,
    TEACHER, WAITER
}
