package money.calculator.MoneyCalculator.model.insurance;

public enum ProSport {
    NONE, ATHLETICS, ARCHERY, BADMINTON, BASKETBALL, BOXING, CHESS, DIVING, HOCKEY, GOLF, FENCING,
    FOOTBALL, GYMNASTICS, KARATE, RUNNING, RUGBY, SKIING, TENNIS, TRIATHLON, POWERLIFTING, CROSSFIT,
    WEIGHTLIFTING
}
